build:
  version: "3.0"

accounts:
  message: "Accounts service International Bank related Development API"
  contactDetails:
    name: "Tuan Bin - Developer"
    email: "tuanbin007@gmail.com"
  onCallSupport:
    - 0819758697
    - 3847893474