build:
  version: "2.0"

accounts:
  message: "Accounts service International Bank related QA API"
  contactDetails:
    name: "Bin - QA Lead"
    email: "bin007@gmail.com"
  onCallSupport:
    - 3121321323
    - 5653634665