build:
  version: "1.0"

loans:
  message: "Loans service International Bank related Production API"
  contactDetails:
    name: "Andreas - Product Owner"
    email: "andreas@gmail.com"
  onCallSupport:
    - 3134443245
    - 9698976986